//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2001206945_VanHuuDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdersId { get; set; }
        public string OrdersName { get; set; }
        public Nullable<int> ProductsId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Statuss { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
