//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2001206945_VanHuuDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UsersId { get; set; }
        public string UsersName { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
